optimizely/react-sdk

- CHANGELOG.md
> chore: Prepare for 1.0.0 release

- .travis.yml
- README.md
Add lint rule for spell checking markdown files
> add mdspell

- CHANGELOG.md
- package.json
- src/client.spec.ts
- src/client.ts
- yarn.lock
- Updated minor version of core SDK (`@optimizely/optimizely-sdk`) dependency which, for unrecognized events sent via `.track()`, will impact the log levels in this SDK as well.
- Bumps the version to `1.2.0-alpha.1`
- Updates changelog
> chore(react-sdk): Prepare for 1.2.0-alpha.1 release

- src/Context.ts
- src/Experiment.spec.tsx
- src/Experiment.tsx
- src/Feature.spec.tsx
- src/Feature.tsx
- src/Provider.tsx
- src/Variation.tsx
- src/autoUpdate.ts
- src/client.spec.ts
- src/client.ts
- src/hooks.spec.tsx
- src/index.cjs.ts
- src/index.ts
- src/logOnlyEventDispatcher.ts
- src/withOptimizely.spec.tsx
- src/withOptimizely.tsx
As a follow up to #31 , this PR runs `eslint --fix` on the entire repo.
There are several Typescript `@typescript-eslint` warnings, which we can decide if we want to fix
> chore (ESLINT): eslint fix the whole repo

- src/Variation.tsx
This laughably simple component doesn't need to be a class component.
> chore (OptimizelyVariation): Convert to a functional component

- CHANGELOG.md
- package.json
- src/client.spec.ts
- src/client.ts
- yarn.lock
Prepare for 2.0.0-rc.2 release
> chore: Prepare for 2.0.0-rc.2 release

- CHANGELOG.md
- package.json
- src/client.spec.ts
- src/client.ts
- yarn.lock
> chore: Prepare for 2.0.0 release

- .travis.yml
automate some steps so publishing a release doesn't have to be so manual
> ci: Automate creating a Github release when a tag is pushed

- CHANGELOG.md
- package.json
- src/client.spec.ts
- src/client.ts
> chore: Prepare for 2.3.0 release

- CHANGELOG.md
- package.json
- src/client.spec.ts
- src/client.ts
- yarn.lock
> chore: Prepare for 2.3.1 release

- package.json
- scripts/build.js
- scripts/config.js
- src/client.spec.ts
- yarn.lock
Fixes #79 
I've tried to follow the conventional commit formatting, and I've signed the agreement. :)
> build: adds umd and system build targets

- README.md
Added decide API documentation to the read me and removed the old Experiment and Feature components and hooks from it.
> update: Added decide API documentation to the readme and removed the old APIs from it

- README.md
While adding decide Api documentation to readme, I merged #106 before receiving feedback from @fscelliott . This PR incorporated feedback given by @fscelliott in #106
> update: Updated the Readme

- CHANGELOG.md
- package.json
- src/client.spec.ts
- src/client.ts
- yarn.lock
-  Update Changelog 
-  Prepare for 2.6.2 release
> chore: Prepare for 2.6.2 release

- CHANGELOG.md
- package.json
- src/client.spec.ts
- src/client.ts
- Prepare for 2.7.1-alpha release
> chore: Prepare for 2.7.1-alpha release

- package.json
- yarn.lock
issue : https://github.com/optimizely/react-sdk/issues/103 and https://github.com/optimizely/react-sdk/issues/137
> fix: updated logging package to 0.3.1.

- .github/workflows/integration_test.yml
> fix: react-sdk-e2e-test branch is main

- package.json
- scripts/config.js
- src/client.spec.ts
- src/client.ts
- src/logger.tsx
- src/utils.tsx
- tsconfig.json
- yarn.lock
Removed direct logging dependency from SDK
Imported logging package from `@optimizely/optimizely-sdk`
All unit tests and Integration tests pass.
[OASIS-8220](https://optimizely.atlassian.net/browse/OASIS-8220)
> Chore: Removed logging package from dependencies

- .github/workflows/react.yml
- use GITHUB-OUTPUT instead of set-output
- No changes here
- https://jira.sso.episerver.net/browse/FSSDK-9004
> [FSSDK-9004] [React] Fix set-output warning

- src/client.ts
- Add options param to fetchQualifiedSegments method
- no changes here
- https://jira.sso.episerver.net/browse/FSSDK-9435
> [FSSDK-9435] [React] Add options params to fetchQualifiedSegments

- README.md
- React sdk compatible version is corrected in readme
- Some links in the readme file are updated to latest
- 
- no changes here
- https://jira.sso.episerver.net/browse/FSSDK-9349
> [FSSDK-9349] [React] Update readme

- src/client.spec.ts
- src/client.ts
- Fetch qualifiedsegments in setuser internally, so that it gets called everytime user is updated
- add test for fetchqualifiedsegment method being called internally for each setuser call 
- https://jira.sso.episerver.net/browse/FSSDK-9492
> [FSSDK-9492] [React] Fetch segments in setuser

- src/client.ts
- cleanup unimplemented method getVuid
- No changes here
- https://jira.sso.episerver.net/browse/FSSDK-8740
> [FSSDK-8740] [React] Remove implemented getVuid method

- .eslintrc.js
- .husky/pre-commit
- package.json
- src/Experiment.spec.tsx
- src/Experiment.tsx
- src/Feature.spec.tsx
- src/Feature.tsx
- src/Provider.spec.tsx
- src/client.spec.ts
- src/client.ts
- src/hooks.ts
- src/notifier.spec.ts
- src/notifier.ts
- src/withOptimizely.spec.tsx
- yarn.lock
- Existing lint error fixed.
- Pre commit hook added for automatic lint check
- [FSSDK-10507](https://jira.sso.episerver.net/browse/FSSDK-10507)
> [FSSDK-10507] React SDK - Linter errors

- src/Experiment.spec.tsx
- src/hooks.spec.tsx
- src/logOnlyEventDispatcher.spec.ts
- src/logOnlyEventDispatcher.ts
- src/logger.spec.ts
- src/logger.tsx
- src/utils.spec.tsx
- src/utils.tsx
- Unit tests improvements of all the modules except ["Client & Provider"](https://jira.sso.episerver.net/browse/FSSDK-10439)
- 33 new tests have been added 
- Improvements & deprecated API updates
- 33 new tests have been added along with improvement & deprecated API replacement
- [FSSDK-10616](https://jira.sso.episerver.net/browse/FSSDK-10616)
> [FSSDK-10616] overall test improvement

- CHANGELOG.md
- package.json
- src/client.spec.ts
- src/client.ts
A patch release PR
- [FSSDK-10844](https://jira.sso.episerver.net/browse/FSSDK-10844)
> [FSSDK-10844] Prep for release
