optimizely/react-sdk

CHANGELOG.md
src/client.spec.ts
src/client.ts

Javascript SDK Client version was being sent in dispatched events. Changed it to send React SDK client version.
Manually tested thoroughly

fix: Client version in dispatched event now shows React SDK version instead of underlying Javscript SDK

---

package.json
yarn.lock

Update optimizely-sdk dependency to 3.3.2. This brings in the React Native default logger fix and the fix for error message logged upon bucketed into unallocated space.

chore: Update optimizely-sdk to 3.3.2

---

README.md
package.json
src/Context.ts
src/index.ts
src/withOptimizely.tsx
yarn.lock

Replace usage of `react-broadcast` with the native React Context API.
The `createContext` API appears to be identical in both cases, so this is just a simple swap with adding a type for the `OptimizelyContext` state.
More here: https://reactjs.org/docs/context.html#reactcreatecontext

maintanance (OptimizelyProvider): Replace react-broadcast with the native React context API

---

package.json
src/client.spec.ts
src/client.ts

- Added getOptimizelyConfig support and upgraded version.

feat: getOptimizelyConfig

---

src/Context.ts
src/index.ts
src/withOptimizely.tsx

In preparation for adding support for hooks, export the entire Optimizely Context object.
This PR leaves in the existing Consumer/Provider export pair for backward compatibility.
Partially addresses #6

feat (Context): Export entire OptimizelyContext object

---

CHANGELOG.md
README.md
package.json
src/Experiment.tsx
src/Feature.tsx
src/autoUpdate.ts
src/client.ts
src/hooks.spec.tsx
src/hooks.ts
src/index.ts
yarn.lock

This PR adds a React Hook called `useFeature`, enabling feature usage (with variables) via the hooks interface.
The API designed here is intended to be feature complete with the `<OptimizelyFeature>` component.
Despite just being the new hotness in the React world, there are a couple good reasons to supporting the hooks paradigm in this SDK:
- Easy use of features/variables outside the context of JSX markup
- Allow consumers to avoid using class components (mostly in the interest of bundle size)
- This could also be done by rewriting `<OptimizelyFeature>` as a functional component that itself leverages built in React hooks for state management
_Directly from the README update:_
*arguments*
* `feature : string` Key of the feature
* `options : Object`
* `autoUpdate : boolean` (optional) If …

feat (Hooks): Add useFeature hook

---

CHANGELOG.md
src/Feature.spec.tsx
src/Feature.tsx
src/hooks.ts

Updates `<OptimizelyFeature>` to be a functional component that 
Also adds support for userId and userAttribute overrides.
Addresses #30 
Is this a breaking change? In theory the logic should behave the same, as #28 was designed to implement the same logic as `<OptimizelyFeature>`.
Timing wise, when `isServerSide` is false, the state setting of the correct values of the feature/variables in `useFeature` happens in a second chained _thennable_, rather than the first.
I dont think this should be considered a breaking change (and thus warrant a major release), but I wanted to point it out.

enhancement (<OptimizelyFeature>): Convert to functional component that uses useFeature hook

---

src/autoUpdate.ts
src/hooks.ts

In preparation to introduce a `useExperiment` hook, this PR moves the logic for waiting for the client to become ready, setting initial state, and configuring autoupdate to a shared function, which is passed to `useEffect`
There are a lot of variables that need to be passed, but I think this is much preferable to duplicating the somewhat intricate & nuanced logic that exists there.
Existing unit tests cover this functionality, and more will be added with the introduction of `useExperiment`

chore (Hooks): Move common client ready logic to a separate function

---

CHANGELOG.md
README.md
src/Experiment.spec.tsx
src/Experiment.tsx
src/Feature.tsx
src/hooks.spec.tsx
src/hooks.ts

Adds a `useExperiment` hook and updates `<OptimizelyExperiment>` to use it.
Unit tests added for the new hook, refactored for the `<OptimizelyExperiment>` usage, and new tests added for the passing of overrides.
Addresses #30

feat (Hooks): Add useExperiment hook and refactor <OptimizelyExperiment> to use it

---

.eslintrc.js
src/Feature.spec.tsx
src/Provider.tsx

This rule prevents shadowing variable names that are already declared in the upper scope.
It includes fixes for all the current violations of this.

chore (ESLint): Add no-shadow rule to error

---

src/Experiment.tsx
src/Feature.tsx
src/hooks.ts

Summary:
`Experiment` and `Feature` were refactored to use hooks internally. Now, they access the context set by `OptimizelyProvider` via `useContext`, so there's no need to use `withOptimizely` on them.
In this PR I removed `withOptimizely` from those components, and fixed a log message related to timeout so that it shows the correct timeout when a component timeout prop was used.
Test Plan:
Manually tested, existing unit tests pass

fix: Remove unnecessary withOptimizely usage from Experiment and Feature components, and fix timeout log message

---

package.json
yarn.lock

I'm trying to decrease my dependency install times and this would help de-duplicate my dependency tree. Seems this project only needs `Subtract` which is present in both 2.x and 3.x

Allow more acceptable versions of utility-types

---

src/index.ts

Make `useExperiment` hook available as an export from the top level package module.

fix: Export useExperiment hook from index

---

README.md

Update Initialize Links

---

package.json
yarn.lock

Upgrade optimizely-sdk to 4.2.1, to pull in logging fix

chore: Upgrade optimizely-sdk to v4.2.1

---

src/client.spec.ts
src/client.ts

Fix a few lint and formatting errors that have crept in. These changes came from `npm run lint`.
Existing tests

chore: Fix lint and formatting

---

src/client.spec.ts
src/client.ts

`getFeatureVariables` reaches inside the optimizely-sdk client to access its project config manager, to find what variables are associated with a given feature key. In recent versions of optimizely-sdk, it is no longer necessary to access project config manager to get this information. Features and variables are available via the public, documented `OptimizelyConfig` interface. This PR updates `getFeatureVariables` to use `OptimizelyConfig`.
- Updated unit tests
- Manual testing

refactor(client): In getFeatureVariables, use OptimizelyConfig instead of internal ProjectConfig

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts
yarn.lock

- Upgrade `@optimizely/optimizely-sdk` to compatible-version dependency [4.3.4](https://github.com/optimizely/javascript-sdk/releases/tag/v4.3.4)
- Fixed return type of `getAllFeatureVariables` method in ReactSDKClient
Existing unit tests

chore: Prepare for 2.3.2 release

---

CHANGELOG.md
src/logOnlyEventDispatcher.spec.ts
src/logOnlyEventDispatcher.ts

- Update `logOnlyEventDispatcher` to be compatible with new type definition for `EventDispatcher`, introduced in optimizely-sdk 4.3.4
- Make `logOnlyEventDispatcher` call the done callback
Added unit test

fix: logOnlyEventDispatcher matches expected type and calls done callback

---

CHANGELOG.md
package.json
scripts/build.js

Using the .mjs file extension causes issues using React SDK with Gatsby's Node.js build process. Changing the extension to .es.js appears to resolve those issues.
Created a test Gatsby application, ran `gatsby build`. It completed with no errors.

build: Change file extension for ES module bundle from .mjs to .es.js

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts
yarn.lock

- Upgrade to optimizely-sdk v4.4.0 to include sending flag decisions
- Local bundle and existing unit tests

chore: Prepare for 2.4.0 release

---

src/Experiment.spec.tsx
src/Feature.spec.tsx
src/hooks.spec.tsx
src/hooks.ts

Fix the following bug: when client is initialized with datafile, and no SDK key, OptimizelyExperiment and OptimizelyFeature components don't properly render their decisions.
The issue is in the implementation in hooks and the interaction with the client's ready state (via `isReady`/`onReady`).  When initialized with datafile, the client begins in a non-ready state, but immediately becomes ready on the next tick. But the hook does not recompute the decision when this occurs - it's only recomputing the decision when a `CONFIG_UPDATE` is fired. `CONFIG_UPDATE` is never fired when the instance was initialized with datafile only.
To fix, add an effect in the `useFeature`/`useExperiment` hooks that recomputes the decision after the client becomes ready.
- Manual testing
- Updated unit tests

fix(hooks): Always recompute decision after resolution of ready promise

---

src/client.ts
src/hooks.spec.tsx
src/hooks.ts
src/index.ts

Added a hook which used `decide` api and returns `OptimizelyDecision` object. It also supports auto updating just like other existing hooks
- Manually tested thoroughly
- Added new unit tests

feat(decide): Added useDecide hook

---

package.json
yarn.lock

Update optimizely-sdk dependency to 4.5.0. This brings in the decide API functionality.

chore: Update optimizely-sdk to 4.5.0

---

srcclr.yml

Source clear was also checking for vulnerabilities in dev dependencies. Added a `srcclr.yml` file with `scope:production` to ignore checking dev dependencies.
Source clear tests now show zero vulnerabilites.

chore: Exclude dev dependencies from source clear check

---

src/hooks.spec.tsx
src/hooks.ts
src/index.ts

Renamed decide hook from `useDecide` to `useDecision`.
1. Manually tested thoroughly.
2. Updated unit tests.

refactor: Renamed decide hook from useDecide to useDecision

---

CHANGELOG.md
package.json
yarn.lock

Upgrade `@optimizely/optimizely-sdk` to `v4.6.0`.
- Manually Tested.
- Unit tests pass.

chore: Upgrade Optimizely SDK to 4.6.0

---

CHANGELOG.md
README.md
src/client.ts

Update VariableValuesObject interface to handle JSON type variable.
Issue: https://github.com/optimizely/react-sdk/issues/117

fix: Update VariableValuesObject type to handle JSON type variable

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts
yarn.lock

- upgrate `optimizely-sdk` to [v4.7.0](https://github.com/optimizely/javascript-sdk/releases/tag/v4.7.0)
- prepare for 2.7.0 release

chore: Prepare for 2.7.0 release

---

src/Experiment.spec.tsx
src/Feature.spec.tsx
src/client.ts
src/hooks.spec.tsx
src/hooks.ts

Made the following re-rendering fixes.
1. When SDK is initialized using a datafile, hooks were doing an empty first render and the real decision was returned on the second render. Fixed the SDK to render the correct decision on first render when initialized synchronously.
2. When SDK is initialized with datafile and SDK key both, The hook was being evaluated three times instead of two. Fixed the redundant re-rendering in this case.
Also checked the SDK thoroughly in many combination of sync/async intialization parameters and made fixes where needed.
1. All unit tests pass.
2. Tested all the hooks and components thoroughly with hard coded data file, SDK key and both along with async/sync user initialzation and autoUpdate true/false.

fix: Fixed redundant re-rendering issues

---

CHANGELOG.md
src/client.spec.ts
src/client.ts
src/index.ts

Return type of createInstance was OptimizelyReactSDKClient which is the implementation class. Changed it to the ReactSDKClient interface instead.
- Manually tested thoroughly.
- All existing unit tests pass.
#49

refactor: Return `ReactSDKClient` interface from `createInstance` instead of implementation class

---

CHANGELOG.md
src/index.ts

`ActivateListenerPayload` and `TrackListenerPayload` types were exported from `@optimizely/optimizely-sdk` but were missing in `@optimizely/react-sdk` exports.
Manually tested thoroughly.
All existing unit tests pass.
#121

fix: Exported types `ActivateListenerPayload` and `TrackListenerPayload`

---

.travis.yml

React SDK contains unit tests but its not possible to cover many scenarios using those. We have started working on an E2E test suite in a private repo [here](https://github.com/optimizely/react-sdk-e2e-tests). This PR enables this repo to trigger E2E tests on PRs. E2E test suite is not complete yet, so we are not making the check mandatory. Once we have something significant in that repo, we will make this check mandatory.
Since we were working in the travis config file, we cleaned it up a bit and removed the unnecessary markdown lint which has already been removed from other repos.
Tested the triggering mechanism thoroughly and it appears to be working fine.

chore: Adding E2E tests

---

CHANGELOG.md
src/client.spec.ts
src/client.ts
src/hooks.spec.tsx
src/hooks.ts

Handle React SDK fail catching if ._client returns null when creating new ReactClientSDK instance from `createInstance` function.
Manually tested thoroughly.
All existing unit tests pass.
#134

fix: React SDK null client handling

---

CHANGELOG.md
src/Experiment.spec.tsx
src/Feature.spec.tsx
src/Provider.tsx
src/hooks.ts

Enables usage of hooks within the Optimizely Provider without passing in the `optimizely` prop.
Previously, attempting to use hooks within an Optimizely Provider with a missing `optimizely` prop led to an error being thrown resulting in a crash.
With this change, hooks now return pessimistic results when the `optimizely` prop is `null`.
Addresses this issue: 
- https://github.com/optimizely/react-sdk/issues/152
Also related:
- https://github.com/optimizely/react-sdk/issues/134
Note:
- Instead of returning an "Error" message like requested, we will defer to SDK users to handle the pessimistic values. 
- In certain edge cases, this may be a potentially breaking change for users that expect hooks to throw an error when the `optimizely` prop is null.
---
Refactored tests that expect hooks to …

fix: Hooks gracefully return with an error message when optimizely prop is null

---

CHANGELOG.md
src/hooks.ts

In some scenarios, the useExperiment hook was making two activate calls which results in redundant impression events which has a cost impact on the customers. This PR fixes the redundant activate calls.
- Manually tested thoroughly in many scenarios. 
- All existing tests pass.

fix: Redundant activate calls in useExperiment hook

---

README.md
package.json

- rename client side "full stack" text occurrences according to the ticket instructions
- organize the readme.md file
- No changes here
- https://jira.sso.episerver.net/browse/FSSDK-8959

[FSSDK-8959] [React] Update Non-Code-Path SDK Resources

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts

- minor version bump to prepare for release with this pr changes https://github.com/optimizely/react-sdk/pull/190
- No changes here
- https://jira.sso.episerver.net/browse/FSSDK-8959

Prep for Release 2.9.2

---

.github/workflows/react.yml
package.json
src/client.spec.ts
src/client.ts
yarn.lock

- export fetchQualifiedSegments (asynchronous) method
- make relevant test plans for fetchQualifiedSegments (asynchronous)
- new fetchQualifiedSegments test are added
- https://jira.sso.episerver.net/browse/FSSDK-8941

[FSSDK-8941] [React] Enable ODP Functionality in React Context

---

package.json
src/Provider.tsx
src/autoUpdate.ts
src/hooks.ts
src/logOnlyEventDispatcher.spec.ts
src/logOnlyEventDispatcher.ts
yarn.lock

- JS SDK beta5 removes all old sub-modules. This PR updates the React SDK to use that version and beyond
- All existing tests should pass
- FSSDK-9494

[FSSDK-9494] Update references to old sub modules js-sdk-*

---

.github/workflows/react_release.yml

- https://yarnpkg.com/cli/npm/publish didn't work
- Existing tests should succeed
- FSSDK-9494

[FSSDK-9494] Remove yarn from npm publish

---

.github/workflows/react_release.yml

- Correction to the name of the repository secret used to publish to npm 
I can't believe I didn't see this 🤦Thanks GPT for having me check it.
- All existing tests should pass.
- FSSDK-9494

[FSSDK-9494] Fix the name of the token used to publish

---

.github/workflows/react_release.yml

- Update the release workflow to read the package.json and tag the release in NPM correctly:
- `beta`
- `alpha`
- `rc`
- else `latest`
- I've tested this functionality in this (--dry-run](https://github.com/optimizely/react-sdk/actions/runs/6316523677/job/17151333471)
- Existing code tests should continue to pass.
- FSSDK-9494

[FSSDK-9494] Tag release correctly during publishing

---

README.md

- Changed window datafile variable to optimizelyDatafile 
README doc was out of sync with [Developer docs](https://docs.developers.optimizely.com/feature-experimentation/docs/initialize-sdk-react)
It is a documentation update, thus not needed
- Resolves [FSSDK-9745](https://jira.sso.episerver.net/browse/FSSDK-9745)

fix: updated datafile variable in README

---

src/Experiment.spec.tsx
src/Experiment.tsx

- Fix for #225 where `OptimizelyVariations` with `default` must always be the last child component within an `OptimizelyExperiment`
- Added new tests for coverage
- All existing unit and e2e tests are still expected to pass
- FSSDK-9839

[FSSDK-9839] fix: rendering `default` OptimizelyVariation when not last

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts

- Bump package version
- Update changelog
- All existing tests are expected to pass.
- FSSDK-9654

[FSSDK-9654] chore: Prep for 3.0.0 beta2 release

---

src/Experiment.spec.tsx
src/Feature.spec.tsx
src/Provider.tsx
src/client.spec.ts
src/client.ts
src/hooks.spec.tsx
src/withOptimizely.spec.tsx

- When `OptimizelyProvider` is used without the `user?` or `userId?` props, we should retrieve and use the VUID for `optimizely.setUser()`
- Refactored logic from `constructor()` of provider into lifecycle method `componentDidMount()`
- Test updates to support `getVuid()`
- Added types to remove warns.
- Existing and updated unit tests are expected to pass
- Integration and e2e test should continue to pass
- I'd like to review with @jaeopt for AAT function reqs.
- FSSDK-9654

[FSSDK-9654] fix: Default to VUID without user(id) as Provider prop

---

yarn.lock

Bumps [@babel/traverse](https://github.com/babel/babel/tree/HEAD/packages/babel-traverse) from 7.18.11 to 7.23.9.
- [Release notes](https://github.com/babel/babel/releases)
- [Changelog](https://github.com/babel/babel/blob/main/CHANGELOG.md)
- [Commits](https://github.com/babel/babel/commits/v7.23.9/packages/babel-traverse)
---
updated-dependencies:
- dependency-name: "@babel/traverse" dependency-type: indirect ...
- FSSDK-9968

[FSSDK-9968] build(deps): bump @babel/traverse from 7.18.11 to 7.23.9

---

package.json
yarn.lock

- Bump the version of the Optimizely JS SDK
- All tests should continue to pass
- FSSDK-9623

[FSSDK-9623] chore: bump Optimizely JS SDK version to @latest

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts

- Bump version semantic version number of the React SDK
- Update CHANGELOG
- Unit and end-to-end tests should pass
- FSSDK-9623

[FSSDK-9623] chore: prep 3.0.1 release

---

package.json
scripts/config.js
yarn.lock

- rollup-plugin-uglify has not been updated since 2019 and the last version has vulnerable dependencies causing dependabot alerts. Replaced this with terser plugin instead.
- FSSDK-9969

[FSSDK-9969] replace uglify plugin with terser

---

.vscode/launch.json
.vscode/settings.json
package.json
src/Feature.spec.tsx
src/Provider.spec.tsx
src/Provider.tsx
src/client.spec.ts
src/client.ts
src/hooks.ts
yarn.lock

- Addressing #235 and #236 
- Fix and add associated unit tests
- Update the underlying JS SDK to v5.3.0
- Add VS Code test config files
- Make this PR as long as humanly possible.
- Existing unit and integration tests are expected to pass
- FSSDK-9984 & FSSDK-9985

[FSSDK-9984] fix: initialization and setUser errors

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts

- Bump semantic version of React SDK
- Update CHANGELOG to summarize release changes.
- No code changes; expecting existing unit tests to succeed
- FSSDK-9984

[FSSDK-9984] chore: prepare for release v3.1.0

---

package.json
src/client.spec.ts
src/client.ts
yarn.lock

If the project does not have ODP integration enabled, sdk should not call the fetchQualifiedSegments method.
[FSSDK-10198](https://jira.sso.episerver.net/browse/FSSDK-10198)

[FSSDK-10198] odp not integrated error

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts

Addressed issue - #260 
---
SDK is calling `fetchQuaifiedSegments` method for clients who do not have ODP integrated in their project.  An additional constraint is now in place to avoid that. 
- [FSSDK-10198](https://jira.sso.episerver.net/browse/FSSDK-10198)

[FSSDK-10198] Prepare for release

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts

- Addressed Issue - #232 
- JS SDK version update for RN polyfill support
[FSSDK-10316](https://jira.sso.episerver.net/browse/FSSDK-10316)

[FSSDK-10316] prepare for release

---

README.md
src/hooks.spec.tsx
src/hooks.ts
src/index.ts

- A functional approach to track events.
- `useTrackEvents` hook is exposed similar to the existing `useDecision` hook.
New test cases have been added to support the new functionality
[FSSDK-9871](https://jira.sso.episerver.net/browse/FSSDK-9871)

[FSSDK-9871] Hook for track events

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts

- The new `useTrackEvent` hook is now available for tracking events within functional components. This hook offers all the existing track event functionalities provided by the SDK. ([#268](https://github.com/optimizely/react-sdk/pull/268))
- [FSSDK-9871](https://jira.sso.episerver.net/browse/FSSDK-9871)

[FSSDK-9871] prepare for release

---

src/hooks.spec.tsx
src/hooks.ts

- SDK hooks do not follow the "Rules of Hooks".  Specially the one that states **"Do not call Hooks after a conditional return statement"**. Check the - [Official React Doc](https://react.dev/reference/rules/rules-of-hooks) for more detail
- Broken test cases fixed
- `clientReady` is set to true even though `dataReadyPromise` returns `success == false`, bug fixed
- #196 has been addressed
- Hook test suite is modified to fix some broken mocks and tests
- Manual testing
- [FSSDK-10544](https://jira.sso.episerver.net/browse/FSSDK-10544)

[FSSDK-10544] Refactor Hooks code + tests

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts

- `clientReady` is true even though internal client promise returns `success == false` bug fix
- `useDecision` hook set the update listener on overy render bug fix
- `setForcedDecision` does not reflect the changes in optmizely instance and `useDecision` hook bug fix
- Performance improvements in both hooks and client instance
Existing test should pass 
- [FSSDK-10120](https://jira.sso.episerver.net/browse/FSSDK-10120) - setForcedDecision does not  reflects in Optimizely client instance fixed
- [FSSDK-10544](https://jira.sso.episerver.net/browse/FSSDK-10544) - Hook refactors + hook test improvements
- [FSSDK-10507](https://jira.sso.episerver.net/browse/FSSDK-10507) - Linter errors fixed
- [FSSDk-10440](https://jira.sso.episerver.net/browse/FSSDK-10440) - outdated deps update

[3.2.1] Prep for release

---

src/logger.tsx

- #265 has been addressed. 
- Instead of creating a new log for the React client,  we can reuse the global log that `Optimizely` already provides with its `getLogger` API. That way we can configure the log system as a whole from a single source. 
- FYI, we are already using `getLogger` for [hooks](https://github.com/optimizely/react-sdk/blob/c16ea02cb423c78b9de09b2e78e0d40b590ee38a/src/hooks.ts#L27) and [providers](https://github.com/optimizely/react-sdk/blob/c16ea02cb423c78b9de09b2e78e0d40b590ee38a/src/Provider.tsx#L26C1-L26C50).
[FSSDK-10554](https://jira.sso.episerver.net/browse/FSSDK-10554)

[FSSDK-10554] Can't set log level error

---

CHANGELOG.md
package.json
src/client.spec.ts
src/client.ts

- Multiple instances of the Logger make the log system unconfigurable - bug fix. ([#276](https://github.com/optimizely/react-sdk/pull/276))
[FSSDK-10554](https://jira.sso.episerver.net/browse/FSSDK-10554)

[FSSDK-10554] prep for release

---

.gitignore
src/Provider.spec.tsx
src/Provider.tsx
src/client.spec.ts
src/client.ts

Significant improvements were made to the test coverage of the "Client" and "Provider files.
- Provider Coverage: Increased from 72.34% to 100%
- Client Coverage: Improved from 81.4% to 99.27% by restructuring and adding tests for various methods
- Test Additions: A total of 52 new tests were added, covering previously missing cases and deprecated API updates.
The coverage reports have been generated with the help of "Istanbul" that is the default coverage tool of "Jest". Here are the commands that I have used to generate the coverage report - 
```bash
npx jest --coverage -- client.spec.ts
npx jest --coverage -- provider.spec.tsx
```
A total of 52 new tests were added, covering previously missing cases and deprecated API updates.
- …

[FSSDK-10439] client provider test

---

.github/workflows/react.yml
package.json

Test coverage report job added
- [FSSDK-10437](https://jira.sso.episerver.net/browse/FSSDK-10437)

[FSSDK-10437] jest coverage report job addition

---

src/client.ts

React SDK sets client.isClientReady property to true immediately if datafile presents in the config, before projectConfigManager gets ready, which should not be the case. 
[FSSDK-10730](https://jira.sso.episerver.net/browse/FSSDK-10730)

[FSSDK-10730] isClientReady logic adjustment

---

src/client.spec.ts
src/client.ts

While checking the second parameter of `OptimizelyReactClient.track`, to decide if its a `userId` or `eventTags`, `overrideAttributes` is set to `undefined` if the second argument is `eventTags`, which should not be the case. userId and attribute overrides are two seperate things.
- Test structure of `track` method of React client has improved
- New test case added to cover this specific scenario
- [FSSDK-8184](https://jira.sso.episerver.net/browse/FSSDK-8184)

[FSSDK-8184] override attribute bug fix of track method

---

.github/workflows/integration_test.yml
src/Provider.spec.tsx
src/Provider.tsx

After upgrading to v3 of the Optimizely React SDK, rendering the `OptimizelyProvider` after calling `setUser` resets the user to a default one unless explicitly provided via the user prop.
Existing tests have been adjusted accordingly.
- [FSSDK-10880](https://jira.sso.episerver.net/browse/FSSDK-10880)
- #286

[FSSDK-10880] override initial user bug adjustment

---

README.md

Doc only update with more instructions for "React Native"
- [FSSDK-10121](https://jira.sso.episerver.net/browse/FSSDK-10121)
- #258

[FSSDK-10121] doc update

---

README.md
package.json
src/withOptimizely.tsx
yarn.lock

- The `utility-types` dependency has been removed and TypeScript's `Omit` function used instead.
- Fixes #298

Remove utility-types dependency
